version: '3'
services:
    php-cli:
        build: .docker/php-cli
        volumes:
            - ./:/app
        working_dir: /app
        restart: "no"

    postgres:
        build: .docker/postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_DB=root
        restart: always

volumes:
    postgres:
